var CustomApplications = [
	"app.terminal",
	"app.multidash",
	"app.gpsspeed",
	"app.aio",
	"app.simpledashboard",
	"app.speedometer",
	"app.vdd",
	"app.tetris",
	"app.snake",
	"app.breakout",
	"app.background",
	"app.multicontroller",
	"app.devtools",
];
